---
- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Install build-essential
  apt:
    name: build-essential
    state: present
  become: yes

- name: Install libkrb5-dev
  apt:
    name: libkrb5-dev
    state: present
  become: yes
