---
- name: Import Node public key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: Set up Node deb apt repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_5.x trusty main'
    state: present
  become: yes

- name: Set up Node deb-src apt repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_5.x trusty main'
    state: present
  become: yes

- name: Install NodeJS
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: yes
