---
- name: Download node-build
  git:
    repo: https://github.com/nodenv/node-build.git
    dest: /build/node-build
  become: yes

- name: Install node-build
  command: ./install.sh
  args:
    chdir: /build/node-build
    creates: /usr/local/bin/node-build
  become: yes

- name: Install Node 6.1.0
  command: node-build 6.1.0 /usr/local
  args:
    creates: /usr/local/bin/node
  become: yes
